local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-f>', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
-- vim.keymap.set('n', '<leader><F9>', builtin.live_grep, {})
    -- vim.keymap.set('n', '<leader>ws', builtin.grep_string, { noremap = true })
-- vim.keymap.set('n', '<leader>ws', function()
-- 	builtin.grep_string({ search = vim.fn.input("Grep > ") })
-- end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})